name: Deploy Reserve-Rec-Public Prod

run-name: Deploying ${{ github.ref_name }} (Public) to prod

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Tag of version to be promoted to prod"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      max-parallel: 1
      matrix:
        node-version: [20.x]
    steps:
      ### Checkout GitHub Repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # - shell: bash
      #   env:
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #   run: |
      #     curl -X POST -H 'Content-Type: application/json' $WEBHOOK_URL --data '{"text":"Reserve Rec - Deploy Public Prod"}'

      ### Install if no cache exists ###
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install --silent --frozen-lockfile

      ### Build if no cache exists ###
      - name: Cache Build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: |
            **dist
          key: ${{ github.sha }}-dist
      - name: Run yarn build
        if: steps.cache-build.outputs.cache-hit != 'true'
        env:
          GH_HASH: ${{ github.sha }}
        run: |
          sed 's@localConfigEndpoint@'true'@g' src/env.js.template | sed 's@localGHHash@'"$GH_HASH"'@g' > src/env.js
          yarn build

      ### Setup AWS SAM
      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      ### Assume AWS IAM Role
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      ### SAM Build
      - name: Cache SAM Build
        id: cache-sam-build
        uses: actions/cache@v3
        with:
          path: |
            **.aws-sam
          key: ${{ github.sha }}-sam-cache
      - name: Run sam build
        if: steps.cache-sam-build.outputs.cache-hit != 'true'
        run: |
          sam build --cached

      ### Prevent prompts and failure when the stack is unchanged
      - name: SAM deploy
        env:
          STACK_NAME: ${{ vars.STACK_NAME }}
          DIST_ORIGIN_PATH: "latest"
          API_GATEWAY_ID: ${{ vars.API_GATEWAY_ID }}
          ENV: ${{ vars.ENVIRONMENT_STAGE }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          API_STAGE: ${{ vars.API_STAGE }}
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          AWS_CERTIFICATE_ARN: ${{ vars.AWS_CERTIFICATE_ARN }}
          API_CACHE_POLICY_ID: ${{ vars.API_CACHE_POLICY_ID }}
        run: |
          sam deploy --stack-name $STACK_NAME --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides \
          DistOriginPath=$DIST_ORIGIN_PATH \
          ApiGatewayId=$API_GATEWAY_ID \
          Env=$ENV \
          AWSRegion=$AWS_REGION \
          ApiStage=$API_STAGE \
          EnvDomainName=$DOMAIN_NAME \
          DomainCertificateArn=$AWS_CERTIFICATE_ARN \
          ApiCachePolicyId=$API_CACHE_POLICY_ID \

      ### Upload dist to S3 ###
      - name: Deploy to S3
        env:
          S3_BUCKET: ${{ vars.STACK_NAME }}-${{ vars.ENVIRONMENT_STAGE }}
          DIR_NAME: ${{ github.sha }}
        run: |
          aws s3 sync dist s3://$S3_BUCKET/$DIR_NAME
          aws s3 rm s3://$S3_BUCKET/ --recursive --exclude "*" --include "latest/*"
          aws s3 sync dist s3://$S3_BUCKET/latest

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"

      # - shell: bash
      #   env:
      #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      #   run: |
      #     curl -X POST -H 'Content-Type: application/json' $WEBHOOK_URL --data '{"text":"Reserve Rec - Deploy Public Prod Complete"}'
